### ISSUE TITLE
ERROR: LoadError: UndefVarError: JULIA_HOME not defined

### ISSUE THREAD

**Issue by zsz00** [JuliaInterop/Cxx.jl#398]
(v1.0) pkg> add Cxx#master

Building Cxx ─→ `~/.julia/packages/Cxx/81BGP/deps/build.log`
┌ Error: Error building `Cxx`: 
│ [ Info: Building julia binary build
│ ERROR: LoadError: UndefVarError: JULIA_HOME not defined
│ Stacktrace:
│  [1] top-level scope at logging.jl:312
│  [2] top-level scope at /root/.julia/packages/Cxx/81BGP/deps/build.jl:43
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1041
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:388
│  [7] top-level scope at none:0
│ in expression starting at /root/.julia/packages/Cxx/81BGP/deps/build.jl:42
│ writing path.jl file
│ Tuning for julia installation at /root/julia-1.0/bin with sources possibly at /root/julia-1.0/bin/../..
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069

Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by cdsousa** [comment]
It is still not working with non-"built from source" Julia installations. That error could be simply corrected by putting`Sys.BINDIR` in the place of `JULIA_HOME` in the deps/build.jl file, but nevertheless everything else is still not prepared to compile the LLVM/Clang 6.0.0 need but normal downloaded Julia installations.

I'm slowly (just a couple of minute a day) trying to figure out how to use BinaryBuilder.jl to ship compiled LLVM/Clang for Cxx in downloaded Julia installations.

**Comment by Gnimuc** [comment]
@cdsousa I tried a binary build on Linux, after tweaking the [makefile](https://github.com/Gnimuc/Cxx.jl/blob/binary-build/deps/BuildBootstrap.Makefile), it's basically working.

## Prerequisites
Julia binary is not shipped with Clang and LLVM tools, so the first step is to build Julia 1.0 compatible LLVM tools and Clang. Although LLVMBuilder has released several versions of LLVM binaries, it looks like none of them are 1.0 compatible. Fortunately, I've released a [1.0 compatible version](https://github.com/ihnorton/Clang.jl/releases) a while ago for Clang.jl, so we can use it here. Now, we have LLVM tools, build/libs, build/includes.

## Rebuild Clang
Using the Clang built via LLVMBuilder directly, I got weird link errors like `cannot find symbol for dump()`, so I just rebuild Clang. To build Clang, we need LLVM&cfe source code: https://github.com/Gnimuc/Cxx.jl/blob/binary-build/deps/download.jl#L42-L56. We also download Julia source code(`src/support`). After building Clang, we have Clang build/libs and build/includes. 

## Build boostrap & libcxxffi
From the source code, we have Clang src/libs, src/include and LLVM src/include. We also have Julia libs and includes that are shipped with Julia binary by default. Now, just tweak those variables in  `BuildBootstrap.Makefile` to the correct path and it's good to go.
 
## Troubleshooting
if CMake complains about `workspace/destdir/XXX cannot find`, you may need to tell CMake where those LLVM tools live in or manually copy-pasting those LLVM tools to `workspace/destdir` can also do the trick.

**Comment by twadleigh** [comment]
@cdsousa, have you made much progress on the `BinaryBuilder` front? I have some motivation to push that effort forward and might be able to carve out some time for it.

**Comment by Gnimuc** [comment]
Here is the routine I used for building libcxxffi: https://github.com/Gnimuc/LLVMBuilder/tree/libcxxffi-cmake#build-libcxxffi

But I'm still not crystal clear about what's the canonical way to build Julia1.0-compatible LLVM/Clang binaries. You may notice that the BB version I used is `0.0.4 #e973095`, but that's not mandatory I guess. I also tried BB-0.1.0, but with no luck, see related reports in [this issue](https://github.com/staticfloat/LLVMBuilder/issues/34). It's possible that I just did something wrong, but I don't have time to look into that, since building LLVM/Clang is very time consuming, it costs about 30min for a single target on my machine, not to mension that BB binaries also need to be redownload when switching versions. 

Given prebuild LLVM/Clang binaries, it's actually not hard to build libcxxffi, just cross-compile bootstrap.cpp and link LLVM/Clang and Julia. As for Windows support, the last thing that I can't figure out is the compatibility of Windows Julia binaries. I guess a potential solution would be https://github.com/JuliaLang/julia/issues/30338.
